### ISSUE TITLE
Reference the variable before assignment

### ISSUE THREAD

**Issue by foxtrot-dfm1** [RedTurtle/design.plone.contenttypes#138]
https://github.com/RedTurtle/design.plone.contenttypes/blob/bcc2b2c0344a6151b4c08afae3440561449052b8/src/design/plone/contenttypes/upgrades/upgrades.py#L969

I think the `brain` var was not defined at this point, maybe it will create a failure during the upgrade step

**Comment by cekk** [comment]
i agree with you, but i don't know why it didn't break during upgrade-steps

**Comment by foxtrot-dfm1** [comment]
So may be that code was not reached?
