### ISSUE TITLE
Path sbagliato in widget 

### ISSUE THREAD

**Issue by nzambello** [RedTurtle/design.plone.contenttypes#4]
Aggiungendo un contenuto  Persona
nel campo Organizzazioni  di riferimento, il path di default è `/istrazione` quando ci aspettiamo `/amministrazione`
Non ho trovato riferimenti nel codice 🤔

**Comment by deodorhunter** [comment]
@nzambello si e' un bug del widget, non ho mai capito perche' faccia cosi'.
line 29, interfaces/persona.py
```
    organizzazione_riferimento = RelationList(
        title=_(
            u"organizzazione_riferimento",
            default=u"Organizzazione di riferimento",
        ),
        value_type=RelationChoice(
            title=_(u"Organizzazione di riferimento"),
            vocabulary="plone.app.vocabularies.Catalog",
        ),
        required=True,
    )
    form.widget(
        "organizzazione_riferimento",
        RelatedItemsFieldWidget,
        pattern_options={
            "maximumSelectionSize": 1,
            "selectableTypes": ["Unita organizzativa"],
            "basePath": "/amministrazione",
        },
    )
```

Commentalo per il momento e ricarica i ct, dobbiamo scoprire perche' solo alcuni widget si smaialano (e qualcuno mi sta dando problemi su volto)

**Comment by cekk** [comment]
@nzambello direi che questo è obsoleto
